namespace :db do
	desc "Create initial About page row"
	task :create_about_row => :environment do

		col1 = '<p>The Berkeley Beacon is Emerson College’s independent, student-run newspaper. Founded in 1947, the weekly publishes in print on Thursdays each fall and spring semester and online daily. The paper is a chronicle of life at Emerson &mdash; covering student government politics, campus performances, and school-wide trends.</p><p>In recent years, the paper’s reporting has revealed racial biases in the college’s tenure practices, performance space struggles for student groups, and food code violations in the campus dining facilities.</p><p>In 2011, the paper took strides in increasing its online presence by launching the <a href="http://www.niemanlab.org/2012/04/emerson-college-student-paper-completes-a-fully-responsive-mobile-friendly-redesign/">first college newspaper website with a responsive design</a>, following The Boston Globe’s release of BostonGlobe.com, the world’s first HTML5, responsive-designed newspaper site.</p><p><strong>Email:</strong> <a href="mailto:contact@berkeleybeacon.com">contact@berkeleybeacon.com</a></p><p><strong>Phone:</strong> 617-855-NEWS <em>(6397)</em></p><p><strong>Address:</strong>	<a href="http://maps.google.com/maps?q=150+Boylston+Street,+Boston,+MA&hl=en&sll=37.0625,-95.677068&sspn=55.543096,114.169922&oq=150+boy&t=v&hnear=150+Boylston+St,+Boston,+Massachusetts+02116&z=17">		Piano Row, Rm. L-145		<br/>150 Boylston St.		<br/>Boston, MA 02116</a></p>'
		col2 = '<p>	<strong>Editor-in-Chief</strong>	<a href="/staff/claire-nobles">Claire Nobles</a>	<br><a href="mailto:editor@berkeleybeacon.com">editor@berkeleybeacon.com</a></p><p>	<strong>Managing Editors</strong>	<a href="/staff/anna-buckley">Anna Buckley</a>, <em>Lifestyle & Sports</em><br/>		<a href="/staff/christina-jedra">Christina Jedra</a>, <em>News & Opinion</em><br>	<a href="/staff/jason-mandanjian">Jason Mandanjian</a>, <em>Arts, Events, & Features</em></p><p>	<strong>News Editor</strong>	<a href="/staff/dina-kleiner">Dina Kleiner</a></p><p>	<strong>Opinion Editor</strong>	<a href="/staff/hunter-harris">Hunter Harris</a></p><p>	<strong>Arts Editor</strong>	<a href="/staff/erica-mixon">_</a></p><p>	<strong>Lifestyle Editor</strong>	<a href="/staff/victoria-hulbert">Victoria Hulbert</a></p><p>	<strong>Photography Editor</strong>	<a href="/staff/jack-adams">Jack Adams</a></p><p>	<strong>Business Manager</strong>	Crystal Witter</p><p>	<strong>Adviser</strong>	Ric Kahn</p>'
		col3 = '<p>	<strong>Deputy News Editor</strong>	<a href="/staff/laura-king">Laura King</a></p><p>	<strong>Assistant News Editor</strong>	<a href="/staff/david-bumpus">David A. Bumpus</a></p><p>	<strong>Limburg Bureau Chief</strong>	<a href="/staff/martha-schick">Martha Schick</a></p><p>	<strong>Assistant Opinion Editor</strong>	<a href="/staff/dan-blomquist">Dan Blomquist</a></p><p>	<strong>Deputy Sports Editor</strong>	<a href="/staff/claire-nobles">Claire Nobles</a></p><p>	<strong>Deputy Arts Editor</strong>	<a href="/staff/cathleen-cusachs">Cathleen Cusachs</a></p><p>	<strong>Deputy Lifestyle Editor</strong>	<a href="/staff/rebecca-szkutak">Rebecca Szkutak</a></p><p>	<strong>Assistant Lifestyle Editor</strong>	<a href="/staff/agatha-kereere">Agatha Kereere</a></p><p>	<strong>Deputy Photography Editor</strong>	<a href="/staff/evan-walsh">Evan Walsh</a></p><p>	<strong>Copyeditors</strong>	Shannon Bushee <br>	Holly Kirkman <br>	Jillian Meehan <br></p><p>	<strong>Designer</strong>	Aren Kabarajian <br></p><p>	<strong>Illustrators</strong>	Holly Kirkman <br>	Abigail Shenker</p>'

		about = About.create!(col1: col1, col2: col2, col3: col3)

	end
end