plugins:
  - paste
  - link
  - image
theme: modern
toolbar1: bold italic | removeformat link image | blockquote alignleft aligncenter alignright | undo redo
# theme_advanced_buttons1:
#   - mylistbox
#   - mysplitbutton
#   - bold
#   - italic
#   - underline
#   - separator
#   - strikethrough
#   # - justifyleft
#   # - justifycenter
#   # - justifyright
#   # - justifyfull
#   - bullist
#   - numlist
#   - undo
#   - redo
#   - link
#   - unlink
#   - image
#   - code
# theme_advanced_toolbar_location: top
# theme_advanced_toolbar_align: left
# theme_advanced_statusbar_location: bottom
# width: 940
# height: 400
# paste_auto_cleanup_on_paste: true
# paste_remove_styles: true
# paste_remove_styles_if_webkit: true
# paste_strip_class_attributes: true
# convert_urls: false
# relative_urls: false
# remove_script_host: false